#!/bin/bash

# Deploys a built docker image, by uploading it to the container registry and then nudging the deployment's tag ref
# Requires that doctl registry and kubectl are both authenticated

APP=blockworld

# Docker Image in DigitalOcean Container Registry
IMAGE=registry.digitalocean.com/tangerine/shared
TAGPREFIX="$APP-"

# Name of the deployment (assumes the default namespace)
DEPLOYMENT=$APP

# Named container in that deployment
CONTAINER=$APP

if [ "$1" = "" ]; then
    echo "Usage: $0 (tag)"
    exit 1
fi

IMAGE_FULL="$IMAGE:$TAGPREFIX$1"

docker push $IMAGE_FULL
kubectl set image deployment/$DEPLOYMENT "$CONTAINER=$IMAGE_FULL" --record
kubectl rollout status deployment/$DEPLOYMENT
