#!/bin/bash

# Runs a built image locally, for testing the container

APP=blockworld

# Docker Image in DigitalOcean Container Registry
IMAGE=registry.digitalocean.com/tangerine/shared
TAGPREFIX="$APP-"

if [ "$1" = "" ]; then
    echo "Usage: $0 (tag)"
    exit 1
fi

IMAGE_FULL="$IMAGE:$TAGPREFIX$1"

docker run -d -p 3000:3000 -t $IMAGE_FULL