#!/usr/bin/env node
var debug = require('debug')('my-application');
var server = require('../src/server/app');

console.log('Server listening on port', process.env.PORT || 3000)
server.listen(process.env.PORT || 3000);